import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Faq from '../components/Faq'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'
import Pricing from '../components/Pricing'
import styles from '../styles/Home.module.css'
import Testimonial from '../components/Testimonial'
import Team from '../components/Team'
import Contact from '../components/Contact'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Hero/>
      <Features/>
      <About/>
      <Pricing/>
      <Faq/>
      <Testimonial/>
      <Team/>
      <Contact/>
      <Footer/>
     
    </div>
  )
}
